spring.application.name=movie-service
server.port=8083
# ===============================
# ORACLE DATABASE CONNECTION
# ===============================
spring.datasource.url=jdbc:oracle:thin:@localhost:1521/XEPDB1
spring.datasource.username=icinemas
spring.datasource.password=icinemas123
spring.datasource.driver-class-name=oracle.jdbc.OracleDriver

# ===============================
# JPA & HIBERNATE CONFIG
# ===============================
spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.OracleDialect

# Format SQL in logs (optional)
spring.jpa.properties.hibernate.format_sql=true

